# Generated by Django 5.0.14 on 2025-04-30 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csrgenerator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSRGeneratorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('dns_san', models.TextField()),
                ('ip_san', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='csrgenerator',
            name='user',
        ),
        migrations.DeleteModel(
            name='CSRGeneratorSettings',
        ),
        migrations.DeleteModel(
            name='CSRGenerator',
        ),
    ]
