# Generated by Django 5.2 on 2025-06-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Token del bot de Slack', max_length=255)),
                ('ia_token', models.CharField(help_text='Token para el modelo de IA', max_length=255)),
                ('bot_status', models.BooleanField(default=True, help_text='Estado del bot (encendido o apagado)')),
            ],
        ),
    ]
